/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0+dev-14-g1e2c2edab
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AddCollaboratorOption : AddCollaboratorOption options when adding a user as a collaborator of a repository

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AddCollaboratorOption {
  #[serde(rename = "permission")]
  permission: Option<String>
}

impl AddCollaboratorOption {
  /// AddCollaboratorOption options when adding a user as a collaborator of a repository
  pub fn new() -> AddCollaboratorOption {
    AddCollaboratorOption {
      permission: None
    }
  }

  pub fn set_permission(&mut self, permission: String) {
    self.permission = Some(permission);
  }

  pub fn with_permission(mut self, permission: String) -> AddCollaboratorOption {
    self.permission = Some(permission);
    self
  }

  pub fn permission(&self) -> Option<&String> {
    self.permission.as_ref()
  }

  pub fn reset_permission(&mut self) {
    self.permission = None;
  }

}



