/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0+dev-14-g1e2c2edab
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// CommitAffectedFiles : CommitAffectedFiles store information about files affected by the commit

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CommitAffectedFiles {
  #[serde(rename = "filename")]
  filename: Option<String>
}

impl CommitAffectedFiles {
  /// CommitAffectedFiles store information about files affected by the commit
  pub fn new() -> CommitAffectedFiles {
    CommitAffectedFiles {
      filename: None
    }
  }

  pub fn set_filename(&mut self, filename: String) {
    self.filename = Some(filename);
  }

  pub fn with_filename(mut self, filename: String) -> CommitAffectedFiles {
    self.filename = Some(filename);
    self
  }

  pub fn filename(&self) -> Option<&String> {
    self.filename.as_ref()
  }

  pub fn reset_filename(&mut self) {
    self.filename = None;
  }

}



