/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0+dev-14-g1e2c2edab
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DismissPullReviewOptions : DismissPullReviewOptions are options to dismiss a pull review

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DismissPullReviewOptions {
  #[serde(rename = "message")]
  message: Option<String>
}

impl DismissPullReviewOptions {
  /// DismissPullReviewOptions are options to dismiss a pull review
  pub fn new() -> DismissPullReviewOptions {
    DismissPullReviewOptions {
      message: None
    }
  }

  pub fn set_message(&mut self, message: String) {
    self.message = Some(message);
  }

  pub fn with_message(mut self, message: String) -> DismissPullReviewOptions {
    self.message = Some(message);
    self
  }

  pub fn message(&self) -> Option<&String> {
    self.message.as_ref()
  }

  pub fn reset_message(&mut self) {
    self.message = None;
  }

}



