/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0+dev-14-g1e2c2edab
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GitServiceType : GitServiceType represents a git service

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GitServiceType {
}

impl GitServiceType {
  /// GitServiceType represents a git service
  pub fn new() -> GitServiceType {
    GitServiceType {
    }
  }

}



