/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0+dev-14-g1e2c2edab
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NotifySubjectType : NotifySubjectType represent type of notification subject

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NotifySubjectType {
}

impl NotifySubjectType {
  /// NotifySubjectType represent type of notification subject
  pub fn new() -> NotifySubjectType {
    NotifySubjectType {
    }
  }

}



