/* 
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.18.0+dev-14-g1e2c2edab
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ReviewStateType : ReviewStateType review state type

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ReviewStateType {
}

impl ReviewStateType {
  /// ReviewStateType review state type
  pub fn new() -> ReviewStateType {
    ReviewStateType {
    }
  }

}



